import { Inter } from "next/font/google";
import "./globals.css";
import {Sheet} from '@mui/joy';
import Navbar from '../components/Navbar';
import Container from '@mui/joy/Container';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Costing Nextjs App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Container maxWidth="xl" sx={{my:2}}>
          {children}
        </Container>
      </body>
    </html>
  );
}
